//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

func main() {
	f, err := os.Open("/tmp/glyphlist.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	out, err := os.Create("pdf/glyphlist.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by cmd/genglyphlist; DO NOT EDIT.")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "package pdf")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "// glyphMap maps Adobe glyph names to Unicode runes.")
	fmt.Fprintln(out, "// Source: https://github.com/adobe-type-tools/agl-aglfn/blob/master/glyphlist.txt")
	fmt.Fprintln(out, "var glyphMap = map[string]rune{")

	count := 0
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		parts := strings.SplitN(line, ";", 2)
		if len(parts) != 2 {
			continue
		}
		name := parts[0]
		// The hex value may have multiple code points separated by space.
		// We only use single-codepoint mappings for a rune map.
		hexParts := strings.Fields(parts[1])
		if len(hexParts) != 1 {
			continue
		}
		cp, err := strconv.ParseInt(hexParts[0], 16, 32)
		if err != nil || cp > 0x10FFFF {
			continue
		}
		fmt.Fprintf(out, "\t%q: 0x%04X,\n", name, cp)
		count++
	}

	fmt.Fprintln(out, "}")
	fmt.Fprintf(os.Stderr, "Generated %d glyph mappings\n", count)
}
